//Array.from, Object.assign, Object.is, Number.isNaN, Array.of, Array#find, Array#findIndex, String#includes, String#startsWith, String#endsWith
Array.from||function(){var b=Object.defineProperty,a=function(l){if(null==l)throw TypeError();var g=Object(l),d=1<arguments.length?arguments[1]:void 0,h=2<arguments.length?arguments[2]:void 0,c=!0;if(void 0===d)c=!1;else if("function"!=typeof d)throw TypeError();var a,e,f,n;f=Number(g.length);f=(n=f!=f?0:0!=f&&isFinite(f)?(0>f?-1:1)*Math.floor(Math.abs(f)):f,0>=n?0:Math.min(n,9007199254740991));var m;try{m=(new this,!0)}catch(p){m=!1}n=m?new this(f):Array(f);for(m=0;f>m;)m in g&&(a=g[m],e=c?d.call(h,
a,m,g):a,b?b(n,m,{value:e,writable:!0,enumerable:!0,configurable:!0}):n[m]=e),++m;return n.length=f,n};b?b(Array,"from",{value:a,configurable:!0,writable:!0}):Array.from=a}();
Array.of||function(){var b=Object.defineProperty,a=function(){var a,g=arguments,d=g.length;try{a=(new this,!0)}catch(h){a=!1}for(var c=a?new this(d):Array(d),k=0;d>k;)a=g[k],b?b(c,k,{value:a,writable:!0,enumerable:!0,configurable:!0}):c[k]=a,++k;return c.length=d,c};b?b(Array,"of",{value:a,configurable:!0,writable:!0}):Array.of=a}();
(function(){if(!Array.prototype.find){var b=function(b,g){var d=Object(this),a=0>d.length?0:d.length>>>0;if(0!==a){if("function"!=typeof b)throw new TypeError("Array#find: predicate must be a function");for(var c,k=0;a>k;k++)if(k in d&&(c=d[k],b.call(g,c,k,d)))return c}};if(Object.defineProperty)try{Object.defineProperty(Array.prototype,"find",{value:b,configurable:!0,enumerable:!1,writable:!0})}catch(a){}Array.prototype.find||(Array.prototype.find=b)}})(this);
(function(){if(!Array.prototype.findIndex){var b=function(b){var a=Object(this),d=a.length>>>0;if(0===d)return-1;if("function"!=typeof b)throw new TypeError("Array#findIndex: predicate must be a function");for(var h=1<arguments.length?arguments[1]:void 0,c=0;d>c&&c in a;c++)if(b.call(h,a[c],c,a))return c;return-1};if(Object.defineProperty)try{Object.defineProperty(Array.prototype,"findIndex",{value:b,configurable:!0,writable:!0})}catch(a){}Array.prototype.findIndex||(Array.prototype.findIndex=b)}})(this);
(function(){Object.assign||(Object.assign=function(b,a){var l,g,d;b=Object(b);for(l=1;l<arguments.length;++l){a=Object(arguments[l]);d=Object.keys(Object(a));for(g=0;g<d.length;++g)b[d[g]]=a[d[g]]}return b})})();Number.isNaN||(Number.isNaN=function(b){return b!==b});
Object.is||(Object.is=function(b,a){return 0===b&&0===a?1/b===1/a:b===a?!0:Number.isNaN(b)&&Number.isNaN(a)?!0:!1});
String.prototype.includes||function(){var b={}.toString,a=function(){try{var a={},b=Object.defineProperty,g=b(a,a,a)&&b}catch(k){}return g}(),l="".indexOf,g=function(a){if(null==this)throw TypeError();var g=String(this);if(a&&"[object RegExp]"==b.call(a))throw TypeError();var c=g.length,k=String(a),e=k.length,f=1<arguments.length?arguments[1]:void 0,f=f?Number(f):0;f!=f&&(f=0);var n=Math.min(Math.max(f,0),c);return e+n>c?!1:-1!=l.call(g,k,f)};a?a(String.prototype,"includes",{value:g,configurable:!0,
writable:!0}):String.prototype.includes=g}();
String.prototype.startsWith||function(){var b=function(){try{var a={},b=Object.defineProperty,h=b(a,a,a)&&b}catch(c){}return h}(),a={}.toString,l=function(b){if(null==this)throw TypeError();var d=String(this);if(b&&"[object RegExp]"==a.call(b))throw TypeError();var h=d.length,c=String(b),k=c.length,e=1<arguments.length?arguments[1]:void 0,e=e?Number(e):0;e!=e&&(e=0);e=Math.min(Math.max(e,0),h);if(k+e>h)return!1;for(h=-1;++h<k;)if(d.charCodeAt(e+h)!=c.charCodeAt(h))return!1;return!0};b?b(String.prototype,
"startsWith",{value:l,configurable:!0,writable:!0}):String.prototype.startsWith=l}();
String.prototype.endsWith||function(){var b=function(){try{var a={},b=Object.defineProperty,h=b(a,a,a)&&b}catch(c){}return h}(),a={}.toString,l=function(b){if(null==this)throw TypeError();var d=String(this);if(b&&"[object RegExp]"==a.call(b))throw TypeError();var h=d.length,c=String(b),k=c.length,e=h;if(1<arguments.length){var f=arguments[1];void 0!==f&&(e=f?Number(f):0,e!=e&&(e=0))}h=Math.min(Math.max(e,0),h)-k;if(0>h)return!1;for(e=-1;++e<k;)if(d.charCodeAt(h+e)!=c.charCodeAt(e))return!1;return!0};
b?b(String.prototype,"endsWith",{value:l,configurable:!0,writable:!0}):String.prototype.endsWith=l}();
